project_name: cloud-connect

before:
  hooks:
    - go mod download

builds:
- main: ./cmd/cloud-connect/main.go
  id: cloud-connect
  binary: cloud-connect
  <<: &config
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags: 
      - -buildid="" -s -w
- main: ./cmd/autoapprover/main.go
  id: autoapprover
  binary: autoapprover
  <<: *config

archives:
  - id: cloud-connect
    builds:
      - cloud-connect
    format_overrides:
      - goos: windows
        format: zip
    name_template: "cloud-connect-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  - id: autoapprover
    builds:
      - autoapprover
    format: zip
    name_template: "autoapprover-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  prerelease: auto

brews:
  - description: CLI for managing transit gateway attachments.
    homepage: https://github.com/telia-oss/cloudconnect
    ids:
      - cloud-connect
    install: |
      bin.install "cloud-connect"
    test: |
      system "#{bin}/cloud-connect --version"
    tap:
      owner: telia-oss 
      name: homebrew-tap
    folder: Formula
